name: Tauri CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    # マトリックスビルドの条件により異なるパッケージのインストール
    - name: Install dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev libsoup2.4-dev

    - name: Install dependencies for macOS
      if: matrix.os == 'macos-latest'
      run: brew install webkitgtk

    - name: Install dependencies for Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install webkit2gtk
        choco install gtk3

    # Rustをセットアップ
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # TauriのCLIとcreate-tauri-appのインストール
    - name: Install Tauri CLI
      run: |
        cargo install create-tauri-app
        cargo install tauri-cli

    # アプリのビルド
    - name: Build Tauri app
      run: cargo tauri build

    # 各プラットフォーム向けにバンドルされるアーティファクトを保存
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tauri-${{ matrix.os }}
        path: src-tauri/target/release/bundle/

  # GitHubリリースへの自動デプロイ
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: tauri-${{ matrix.os }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: src-tauri/target/release/bundle/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
