name: Tauri CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    # マトリックスビルドの条件により異なるパッケージのインストール
    - name: Install dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev libsoup2.4-dev

    # macOS では依存関係のインストールは不要

    # Windows では依存関係のインストールは不要

    # Rustをセットアップ
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # TauriのCLIとcreate-tauri-appのインストール
    - name: Install Tauri CLI
      run: |
        cargo install create-tauri-app
        cargo install tauri-cli

    # アプリのビルド
    - name: Build Tauri app
      run: cargo tauri build

    # 各プラットフォーム向けにバンドルされるアーティファクトを保存
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tauri-${{ matrix.os }}
        path: src-tauri/target/release/bundle/

  # GitHubリリースへの自動デプロイ
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts for Linux
      uses: actions/download-artifact@v3
      with:
        name: tauri-ubuntu-latest
        path: ./artifacts

    - name: Download Artifacts for macOS
      uses: actions/download-artifact@v3
      with:
        name: tauri-macos-latest
        path: ./artifacts

    - name: Download Artifacts for Windows
      uses: actions/download-artifact@v3
      with:
        name: tauri-windows-latest
        path: ./artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
        args: ${{ matrix.args }}
