name: Tauri CI with Cargo and Vanilla JS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Rustをセットアップ
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # 必要であれば、Rust依存パッケージをキャッシュ
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # 必要であれば、Cargoビルドアーティファクトをキャッシュ
    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    # TauriのCLIとcreate-tauri-appのインストール
    - name: Install Tauri CLI
      run: |
        cargo install create-tauri-app
        cargo install tauri-cli

    # Rust/Tauriアプリをビルド
    - name: Build Tauri app
      run: cargo tauri build
